package com.rfsilva.jcodemodel.service.generator.backend;

import com.rfsilva.jcodemodel.dto.ChildEntityDefinition;
import com.rfsilva.jcodemodel.dto.DatabaseType;
import org.springframework.stereotype.Component;

import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

@Component
public class ReadmeFileGenerator implements FileGenerator {

    private static final String FILE_NAME = "README.md";

    @Override
    public String generate(GenerationContext ctx, String outputDir) throws IOException {
        String content = buildReadme(ctx);
        try (FileWriter fw = new FileWriter(outputDir + "/" + FILE_NAME)) {
            fw.write(content);
        }
        return FILE_NAME;
    }

    private String buildReadme(GenerationContext ctx) {
        String entity     = ctx.entityName();
        String lower      = entity.toLowerCase();
        String pkg        = ctx.pkg();
        DatabaseType db   = ctx.databaseType();
        List<ChildEntityDefinition> children = ctx.getDefinition().getChildren();

        StringBuilder sb = new StringBuilder();

        sb.append("# ").append(entity).append(" Service\n\n");
        sb.append("CRUD REST API for **").append(entity).append("** generated by [jcodemodel](https://github.com/rfsilva/jcodemodel).\n\n");

        // Stack
        sb.append("## Stack\n\n");
        sb.append("| Component | Version |\n");
        sb.append("|---|---|\n");
        sb.append("| Java | 21 |\n");
        sb.append("| Spring Boot | 3.2.3 |\n");
        sb.append("| Database | ").append(db.name()).append(" |\n");
        sb.append("| Lombok | latest |\n\n");

        // Getting started
        int port = ctx.backendPort();

        sb.append("## Getting Started\n\n");

        if (db != DatabaseType.H2) {
            sb.append("### 1. Start the database\n\n");
            sb.append("```bash\n");
            sb.append("docker compose up -d\n");
            sb.append("```\n\n");
            sb.append("### 2. Run the application\n\n");
        } else {
            sb.append("### Run the application\n\n");
        }

        sb.append("```bash\n");
        sb.append("./mvnw spring-boot:run\n");
        sb.append("```\n\n");
        sb.append("The application starts on port **").append(port).append("** → `http://localhost:").append(port).append("`\n\n");

        if (db == DatabaseType.H2) {
            sb.append("H2 console: `http://localhost:").append(port).append("/h2-console`  \n");
            sb.append("JDBC URL: `jdbc:h2:mem:").append(lower).append("db`\n\n");
        }

        // Endpoints — parent
        sb.append("## API Endpoints\n\n");
        sb.append("### ").append(entity).append("\n\n");
        sb.append("| Method | Path | Description |\n");
        sb.append("|---|---|---|\n");
        sb.append("| GET | `/api/").append(lower).append("s` | List all |\n");
        sb.append("| GET | `/api/").append(lower).append("s/{id}` | Get by id |\n");
        sb.append("| POST | `/api/").append(lower).append("s` | Create |\n");
        sb.append("| PUT | `/api/").append(lower).append("s/{id}` | Update |\n");
        sb.append("| DELETE | `/api/").append(lower).append("s/{id}` | Delete |\n\n");

        // Endpoints — children
        if (children != null && !children.isEmpty()) {
            for (ChildEntityDefinition child : children) {
                String childName  = child.getEntityName();
                String childLower = childName.toLowerCase();
                sb.append("### ").append(childName).append(" (child of ").append(entity).append(")\n\n");
                sb.append("| Method | Path | Description |\n");
                sb.append("|---|---|---|\n");
                sb.append("| GET | `/api/").append(lower).append("s/{").append(lower).append("Id}/").append(childLower).append("s` | List all |\n");
                sb.append("| GET | `/api/").append(lower).append("s/{").append(lower).append("Id}/").append(childLower).append("s/{id}` | Get by id |\n");
                sb.append("| POST | `/api/").append(lower).append("s/{").append(lower).append("Id}/").append(childLower).append("s` | Create |\n");
                sb.append("| PUT | `/api/").append(lower).append("s/{").append(lower).append("Id}/").append(childLower).append("s/{id}` | Update |\n");
                sb.append("| DELETE | `/api/").append(lower).append("s/{").append(lower).append("Id}/").append(childLower).append("s/{id}` | Delete |\n\n");
            }
        }

        // Package structure
        sb.append("## Package Structure\n\n");
        sb.append("```\n");
        sb.append(pkg.replace('.', '/')).append("/\n");
        sb.append("├── ").append(entity).append("Application.java\n");
        sb.append("├── controller/\n");
        sb.append("├── dto/\n");
        sb.append("├── entity/\n");
        sb.append("├── exception/\n");
        sb.append("├── mapper/\n");
        sb.append("├── repository/\n");
        sb.append("└── service/\n");
        sb.append("```\n");

        return sb.toString();
    }
}
